### ISSUE TITLE
Python 3.8 Breaks Pyznap?

### ISSUE THREAD

**Issue by bebop350** [yboetz/pyznap#51]
Pyznap no longer works, seemingly due an issue with newer versions of Python perhaps.

pastebin of error: https://pastebin.com/m2SggbGR

`[noah@X58NAS ~]$ pyznap --help
Traceback (most recent call last):
  File "/usr/bin/pyznap", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3252, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3235, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3264, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'pyznap==1.4.3' distribution was not found and is required by the application
`
Pyznap throws similar errors when issuing other commands (eg: "sudo pyznap -v snap"). I tried upgrading Python from 3.8.1 to 3.8.1-1 and reinstalling Pyznap, but no joy. I guess I should try downgrading Python?

My system:
Arch Linux 4.19.12.arch1-1
zfs-dkms 0.7.12-1
Python 3.8.1-1 
pyznap 1.4.3 (listed as 1.4.3-1 in the AUR https://aur.archlinux.org/packages/pyznap/)

**Comment by bebop350** [comment]
This is an Arch Linux issue, not a Pyznap issue. My apologies.
Upgrading Python to 3.8 then upgrading python-setuptools, then rebuilding pyznap seems to fix the issue.

**Comment by vtnpp** [comment]
I had the same issue on Arch with `python-setuptools` 1.44.0.0-1 from testing repository. 

`$ sudo pyznap setup`

```
Traceback (most recent call last):
  File "/usr/bin/pyznap", line 6, in <module>
    from pkg_resources import load_entry_point
ModuleNotFoundError: No module named 'pkg_resources'
```

Downgrading to 1.43.0.0-1 and rebuilding [`pyznap`<sup>AUR</sup>](https://aur.archlinux.org/packages/pyznap/) solved the issue.
