### ISSUE TITLE
pyznap 1.6.0 send with pyznap.conf failed

### ISSUE THREAD

**Issue by japamax** [yboetz/pyznap#92]
My Python version is  `Python 3.10.5` and my system is Archlinux

My zfs version :
```
zfs-2.1.5-1
zfs-kmod-2.1.5-1
```

My pyznap.conf :
```
###    SNAPSHOT 3 JOURS + DERNIERE HEURE   ###
[Transcend_256Gb/Root]
        frequent  = 4
        hourly    = 0
        daily     = 3
        weekly    = 3
        monthly   = 11
        yearly    = 3
        snap      = yes
        clean     = yes
        dest      = Seagate_6Tb_Mirror/Backup/Root
        exclude   =

###    BACKUP DERNIER DE LA DERNIERE HEURE   ###
[Seagate_6Tb_Mirror/Backup/Root]
        frequent  = 1
        hourly    = 0
        daily     = 0
        weekly    = 0
        monthly   = 0
        yearly    = 0
        snap      = no
        clean     = yes
        dest      =
        exclude   =

```

Works perfectly manually

```
pyznap send -s Transcend_256Gb/Root -d Seagate_6Tb_Mirror/Backup/Root         
Oct 13 11:36:29 INFO: Starting pyznap...
Oct 13 11:36:29 INFO: Sending snapshots...
Oct 13 11:36:29 INFO: No common snapshots on Seagate_6Tb_Mirror/Backup/Root, sending oldest snapshot Transcend_256Gb/Root@___FIRST_20220514___ (~152.8G)...
   154GiO 3:19:47 [3,50MiO/s] [====================================================>] 101% ETA 0:00:00
   155GiO 3:21:35 [13,2MiO/s] [====================================================>] 101%            
Oct 13 14:58:32 INFO: Updating Seagate_6Tb_Mirror/Backup/Root with recent snapshot Transcend_256Gb/Root@pyznap_2022-10-13_09:30:02_frequent (~0.0B)...
  cannot open 'Transcend_256Gb/Root@pyznap_2022-10-13_09:30:02_frequent': dataset does not exist
Oct 13 14:58:32 ERROR: Error while sending to Seagate_6Tb_Mirror/Backup/Root: cannot receive: failed to read from stream...
Oct 13 14:58:32 INFO: Finished successfully...
```
The  error seems due the  Seagate_6Tb_Mirror/Backup/Root is not mounted

But pyznap send  fails
```
%  pyznap -v send
Oct 13 11:22:51 INFO: Starting pyznap...
Oct 13 11:22:51 INFO: Sending snapshots...
Traceback (most recent call last):
  File "/usr/bin/pyznap", line 33, in <module>
    sys.exit(load_entry_point('pyznap==1.6.0', 'console_scripts', 'pyznap')())
  File "/usr/lib/python3.10/site-packages/pyznap/main.py", line 170, in main
    return _main()
  File "/usr/lib/python3.10/site-packages/pyznap/main.py", line 153, in _main
    send_config(config)
  File "/usr/lib/python3.10/site-packages/pyznap/send.py", line 301, in send_config
    zfs.open(dest_name, ssh=ssh_dest)
  File "/usr/lib/python3.10/site-packages/pyznap/pyzfs.py", line 104, in open
    type = findprops(name, ssh=ssh, max_depth=0, props=['type'])[name]['type'][0]
KeyError: ''
```

**Comment by yboetz** [comment]
Maybe try removing the empty config lines, I'm not sure if that could create problems.

**Comment by japamax** [comment]
OK the error is due to the dest= line with an empty value
`dest      =`

**Comment by yboetz** [comment]
Ok, great that it works now.
